# <center> Homework 1 </center>

# 0. Где мы сейчас?
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Jupyter_logo.svg/1200px-Jupyter_logo.svg.png" width="150">

[Jupyter Notebook](https://jupyter.org/) - интерактивная среда для запуска программного кода в браузере. Удобный инструмент для анализа данных, который используется многими специалистами по data science. Позволяет выполнять отдельные ячейки с кодом, а не всю программу сразу, что очень удобно при знакомстве с данными.

# 1. Python
> Python - это свободный интерпретируемый объектно-ориентированный расширяемый встраиваемый язык программирования очень высокого уровня 

>*(Г.Россум, Ф.Л.Дж.Дрейк, Д.С.Откидач "Язык программирования Python").*

А если без цитат, то питон - это просто очень крутой язык, созданный в 1991 году [Великодушным пожизненным диктатором](https://ru.wikipedia.org/wiki/%D0%92%D0%B5%D0%BB%D0%B8%D0%BA%D0%BE%D0%B4%D1%83%D1%88%D0%BD%D1%8B%D0%B9_%D0%BF%D0%BE%D0%B6%D0%B8%D0%B7%D0%BD%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D0%B4%D0%B8%D0%BA%D1%82%D0%B0%D1%82%D0%BE%D1%80) Гвидо ван Россумом и названный в честь любимого им шоу [Monty Python's Flying Circus](https://en.wikipedia.org/wiki/Monty_Python%27s_Flying_Circus)

<img src="https://advancelocal-adapter-image-uploads.s3.amazonaws.com/image.oregonlive.com/home/olive-media/width2048/img/tv/photo/2018/10/10/montycastjpg-7ef393e2355a42aa.jpg" width="300">

# 2. Anaconda

<img src="https://cdn-images-1.medium.com/max/1600/0*MVkCW8_Bmj-nuAnI.png" width="300">

[Сборка Anaconda](https://www.anaconda.com/products/individual) включает очень много полезных библиотек для анализа данных. 

Среди наиболее популярных библиотек:
 - <a href="http://numpy.org">Numpy</a> - это один из основных пакетов для математических вычислений. Он содержит средства для работы с многомерными массивами и высокоуровневыми математическими функциями
 - <a href="https://www.scipy.org/">SciPy</a> - научные вычисления. Методы оптимизации, интегрирования, модули обработки сигналов и изображений, статистика, линейная алгебра, сплайны, кластеризация и многое другое
 -  <a href="http://pandas.pydata.org/">Pandas</a> - основная библиотека для обработки и анализа данных. Предназначена для данных разной природы - матричных, панельных данных, временных рядов. Претендует на звание самого мощного и гибкого средства для анализа данных с открытым исходным кодом
 - <a href="http://scikit-learn.org/stable/">Scikit-learn</a> - реализация очень многих методов машинного обучения с отличной документацией. 
 - <a href="http://http://matplotlib.org/">matplotlib</a> - хорошая библиотека для визуализации данных

# 3. Задачки

## Задача 1
$N$ хоббитов делят $K$ кусков эльфийского хлеба поровну, не делящийся нацело остаток остается в корзинке у Сэма. Напишите функцию, которая принимает на вход параметры $N$ и $K$ и возвращает два числа: $x$ - cколько кусков эльфиского хлеба достанется каждому хоббиту, и $y$ - сколько кусков остаётся в корзинке.

In [3]:
import math


def share_bread(N, K):
    # your code here
    return K//N, K%N

# если в функции всё верно, то после выполнения этой строчки, не должно выскакивать ошибок
assert share_bread(N=3, K=14) == (4, 2)

(4, 2)


## Задача 2

В копях Мории хоббиты нашли стену, на которой высечены разные натуральные числа. Согласно древним сказаниям, это даты сражений. Хоббиты знают, что сражения происходили только по високосным годам. Помогите хоббитам определить, является ли год с данным числом датой великого сражения. Если это так, то верните строку "YOU SHALL PASS", иначе верните "YOU SHALL NOT PASS". Напомним, что в соответствии с хоббитским календарем, год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.

In [10]:
def leap_year(year):
    if not (year % 4) and (year % 100) and not (year % 400):
        return "YOU SHALL PASS"
    
    else:
        return "YOU SHALL NOT PASS"

assert leap_year(5) == 'YOU SHALL NOT PASS'

## Задача 3
<img src="http://i0.kym-cdn.com/photos/images/original/001/187/255/5e9.gif" width=300>
Для могущественного магического ритуала Гендальфу необходимо быстро подсчитывать площадь своего амулета, который умеет менять размеры. Известно, что амулет имеет форму треугольника и Гендальф знает длину каждой из сторон. Напишите функцию, которая считает площадь амулета по трем сторонам.  

Подсказка: используйте формулу Герона
$$ S = \sqrt{p(p-a)(p-b)(p-c)} $$
$$ p = \frac{a + b + c}{2}$$


In [79]:
import math


def amulet_area(a, b, c):
    # your code here
    p = (a + b + c)/2
    return math.sqrt(p * (p - a) * (p - b) * (p - c))

assert amulet_area(3, 4, 5) == 6

## Задача 4

Хоббиты собираются пешком идти до Мордора и им нужно подсчитать расстояние, которое им предстоит пройти. Хоббиты смогли вспомнить сразу несколько метрик расстояния: евклидово, манхэттена и косинусное, так что ваша задача - напистаь функцию под каждую из них. Важное условие - используйте только базовые функции numpy для решения.


* Евклидово расстояние
$$ d(a, b) = \sqrt{\sum_i (a_i - b_i)^2} $$
* Расстояние Манхэттена
$$ d(a, b) = \sum_i |a_i - b_i| $$
* Косинусное расстояние
$$ d(a, b) = 1 - \frac{a^\top b}{||a||_2\cdot||b||_2}$$

In [77]:
import numpy as np

def cal_euclidean(a, b):    
    return np.sum(np.sqrt([(x - y)**2 for x, y in zip(a, b)]))

def cal_manhattan(a, b):    
    return np.sum(np.abs([x - y for x, y in zip(a, b)]))

'''
А что нам должна показать косинусное расстояние? Оно вообще у меня правильно вычислено? Я правильно понял запись задания? 
'''
def cal_cosine(a: np.ndarray, b: np.ndarray):    
    return 1 - (np.dot(a, b)) /  (np.linalg.norm(a) * np.linalg.norm(b)) 

In [78]:
a = np.random.randint(-10, 10, size=10)
b = np.random.randint(-10, 10, size=10)
print(cal_euclidean(a, b))
print(cal_manhattan(a, b))
print(cal_cosine(a, b))


66.0
66
0.7260646346022763


## Задача 5

Ну и напоследок, еще немного практики numpy, без которой не обходится ни один хоббит.


Создайте случайный array (`np.random.rand()`) длинной 100. Преобразуйте его так, чтобы
* Максимальный элемент(ы) был равен 1
* Минимальный элемент(ы) был равен 0
* Остальные элементы в итнтервале от 0 до 1 остаются прежними

In [83]:
my_array = np.random.rand(100)
my_array[my_array.argmax()] = 1
my_array[my_array.argmin()] = 0
print(np.max(my_array), np.min(my_array))
print(my_array)


1.0 0.0
[0.39238842 0.18367913 0.97360725 0.34958305 0.47710587 0.49496588
 0.785703   0.79086526 0.25415999 0.10800308 0.71195439 0.34764608
 0.81767594 0.08442105 0.81907404 0.1873913  0.90196447 0.06709509
 0.59890333 1.         0.34939083 0.482527   0.12671232 0.38808781
 0.05106957 0.36950345 0.40977844 0.38306645 0.25641712 0.93861204
 0.6095584  0.52991413 0.37389597 0.75770128 0.89712831 0.88632432
 0.10635585 0.25085252 0.36225008 0.5603924  0.50849452 0.11717124
 0.68670581 0.39202871 0.38477329 0.1584023  0.47580913 0.89236418
 0.32498394 0.43983392 0.44941882 0.81973849 0.75619282 0.80374676
 0.21040258 0.99876027 0.14614913 0.32652633 0.24181461 0.19636737
 0.81785587 0.96511447 0.72433643 0.21244529 0.83046135 0.63212047
 0.36149179 0.98061778 0.36383275 0.99632835 0.92449098 0.53753846
 0.5871955  0.59947198 0.89225557 0.21217358 0.85209209 0.20075164
 0.30509311 0.47756811 0.95304527 0.10805042 0.04813698 0.71663281
 0.21090161 0.09742833 0.48335097 0.63517809 0.       

Создайте array размером $5 \times 6$ с целыми числами в интервале [0,50]. Напечатайте колонку, которая содержит максимальный элемент полученной матрицы 

In [116]:
my_array = np.random.rand(5, 6) * 50
selected_column = my_array[:,np.argmax(my_array)%6]
print('Shape: ',my_array.shape)
print('Array')
print(my_array)
print('max element column num: ', np.argmax(my_array)%6)
print(selected_column)

Shape:  (5, 6)
Array
[[24.05559639 40.22791846 30.46179317  4.42300537 20.03301411 20.38868779]
 [36.9200009   6.9182614   3.0646768  46.89461352 29.50497539 35.96978325]
 [12.26690072 33.17971965 18.33342213 47.15979485  4.94353367 27.37969532]
 [17.90087676 36.76676515 40.50572464 24.61473977 46.75770553  6.64355233]
 [37.16277446 27.74232992 22.41995549 42.56475907 15.87626435 27.33838087]]
max element column num:  3
[ 4.42300537 46.89461352 47.15979485 24.61473977 42.56475907]


Напишите функцию, которая принимает на вход матрицу (array) X и возвращает все её уникальные строки в виде новой матрицы.

In [117]:
def get_unique_rows(X):
    # Your code here
    return np.unique(X, axis=0)

In [118]:
X = np.random.randint(4, 6, size=(10,3))
print(X)

[[5 4 5]
 [4 4 4]
 [5 5 5]
 [5 5 5]
 [5 5 5]
 [4 5 4]
 [5 5 4]
 [4 5 5]
 [5 4 4]
 [4 4 4]]


In [119]:
get_unique_rows(X)

array([[4, 4, 4],
       [4, 5, 4],
       [4, 5, 5],
       [5, 4, 4],
       [5, 4, 5],
       [5, 5, 4],
       [5, 5, 5]])